# Replace the "â¯" symbol in the prompt with "â¯â¯"
[character]
format = "[âœ](bold green) "
success_symbol = "[âœ](bold green) "
error_symbol = "[X](bold red) "

[username]
disabled = true

[hostname]
ssh_only = true
format =  "[$hostname](bold red) [â¯](bold green) "

# Directory setttings
[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncate_to_repo = true

[c]
symbol = "î˜ "

[git_status]
conflicted = "!$c[!]($style) "
ahead = "!$c[â†‘]($style) "
behind = "!$c[â†“]($style) "
diverged = "!$c[â†•]($style) "
untracked = "!$c[?]($style) "
stashed = "!$c[$]($style) "
modified = "!$count($style) "
staged = "!$c[+]($style) "
renamed = "!$c[Â»]($style) "
deleted = "!$c[âœ˜]($style) "

[golang]
symbol = "î˜§ "

[lua]
symbol = "î˜  "

[memory_usage]
disabled = false
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ïŒ“ "

[nodejs]
format = "[$symbol($version )]($style) "
symbol = "îœ˜ "

[package]
format = "[$symbol$version]($style) "
symbol = "ï£– "
disabled = false
display_private = true

[python]
symbol = "îˆµ "

[rlang]
symbol = "ï³’ "

[ruby]
symbol = "î‘ "

[rust]
symbol = "î¨ "

[scala]
symbol = "îœ· "

[spack]
symbol = "ğŸ…¢ "
