[character]
format = "[âœ](bold green) "
success_symbol = "[âœ](bold green) "
error_symbol = "[X](bold red) "

[username]
disabled = true

[hostname]
ssh_only = true
format =  "[$hostname](bold red) [â¯](bold green) "

# Directory setttings
[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncate_to_repo = true

[c]
symbol = "î˜ "

[git_status]
format = "[$all_status$ahead_behind]($style)"
conflicted = "~$count($style) "
ahead = "â†‘$count($style) "
behind = "â†“$count($style) "
diverged = "â†•$count($style) "
untracked = "?$count($style) "
stashed = "*$count($style) "
modified = "!$count($style) "
staged = "+$count($style) "
renamed = "âœ$count($style) "
deleted = "âœ˜$count($style) "

[golang]
symbol = "î˜§ "

[lua]
symbol = "î˜  "

[memory_usage]
disabled = false
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ïŒ“ "

[nodejs]
format = "[$symbol($version )]($style) "
symbol = "îœ˜ "

[package]
format = "[$symbol$version]($style) "
symbol = "ï£– "
disabled = false
display_private = true

[python]
symbol = "îˆµ "

[rlang]
symbol = "ï³’ "

[ruby]
symbol = "î‘ "

[rust]
symbol = "î¨ "

[scala]
symbol = "îœ· "

[spack]
symbol = "ğŸ…¢ "

command_timeout=1000
